### ISSUE TITLE
https://prod.liveshare.vsengsaas.visualstudio.com/join?031E0496D395A0020AFDB5DE6F0CB8740ED7

### ISSUE THREAD

**Issue by TatoBig** [PaoloVeliz/MyNvimConfiguration#1]
https://prod.liveshare.vsengsaas.visualstudio.com/join?031E0496D395A0020AFDB5DE6F0CB8740ED7

**Comment by PaoloVeliz** [comment]
https://chartio.com/resources/tutorials/how-to-list-databases-and-tables-in-postgresql-using-psql/#:~:text=To%20view%20all%20of%20the,command%20or%20its%20shortcut%20%5Cl%20.
